version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: on-failure
    container_name: fast_api
    command: python api/app/main.py
    ports:
      - "8000:80"

  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    command: python bot/app/main.py
    environment:
      - TELEGRAM_TOKEN=<TELEGRAM_TOKEN>

  postgres:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: career_assistant
    ports:
      - "5440:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  

volumes:
  postgres_data: